### ISSUE TITLE
Suggestiom: add a worksInEvent property to actions

### ISSUE THREAD

**Issue by TheMonDon** [RobertBorghese/DBM#20]
I'm not sure if this applies to default actions but it might be useful for mods, if it isn't too difficult to do.

Basically if the action is marked as worksInEvent the action will show up inside an event and let you use it

**Comment by RobertBorghese** [comment]
I'm a little confused. Don't all actions show up inside events anyway? 

Is this a option to make it so an action ONLY appears when adding to an event?

**Comment by TheMonDon** [comment]
> I'm a little confused. Don't all actions show up inside events anyway? 
> 
> Is this a option to make it so an action ONLY appears when adding to an event?

Haha I'm also confused by what I meant, but what I think I meant is a thing so that if it's false it doesn't show up in events? And also if something only works in commands it doesn't show up in events

**Comment by TheMonDon** [comment]
Closing this as this entire thing is confusing, I'm not actually sure what I meant anymore lol

**Comment by RobertBorghese** [comment]
@TheMonDon OHH wait, I will say, there is `commandOnly`. Kind of obscure, but makes it so an action is only available in commands and not events.
https://github.com/RobertBorghese/DBM/blob/f070fabceba5de07dcd3bdc4b9e3ccb468b5ec30/actions/check_parameters.js#L8
