### ISSUE TITLE
Triple check BaseInteraction method updates

### ISSUE THREAD

**Issue by RobertBorghese** [RobertBorghese/DBM#28]
isContextMenu -> isContextMenuCommand
isCommand -> isChatInputCommand
isUserContextMenu -> isUserContextMenuCommand
isMessageContextMenu -> isMessageContextMenuCommand

https://discord.js.org/#/docs/discord.js/main/class/BaseInteraction

Some updated from #25

**Comment by TheMonDon** [comment]
isCommand is still a property on interaction, but everything besides a button is a command I think.

**Comment by RobertBorghese** [comment]
All right! Lookin gooood
