### ISSUE TITLE
Update Node.js

### ISSUE THREAD

**Issue by TheMonDon** [RobertBorghese/DBM#31]
I'm unsure what one, maybe current LTS 18.16.0, but since DBM probably won't be updated for a while for new Node version it might be a good idea to change to the pending LTS of 20.x.x slated for LTS in October

**Comment by RobertBorghese** [comment]
Updated on my end, but won't close until I'm sure I've posted build on Steam 👌

**Comment by RobertBorghese** [comment]
Updated on `beta` branch. 👍
