### ISSUE TITLE
Structures from the API cannot be edited directly.

### ISSUE THREAD

**Issue by TheMonDon** [RobertBorghese/DBM#32]
To do so, you can create a new structure (a builder) using the .from() method:
```
const newEmbed = EmbedBuilder.from(embed).setTitle("title")
const newRow = ActionRowBuilder.from(row).addComponents(component)
```

**Comment by RobertBorghese** [comment]
Theres a couple actions with `ActionRowBuilder`, so not closing this yet

**Comment by RobertBorghese** [comment]
Found and fixed some `ActionRowBuilder` issues! The only other "Builder" being used is `AttachmentBuilder`, but that's being created from scratch in both cases. So should work, I'll close after I test those.
