### ISSUE TITLE
Fuck it, Typescript Support

### ISSUE THREAD

**Issue by RobertBorghese** [RobertBorghese/DBM#41]

**Comment by TheMonDon** [comment]
Oh no almeida got to you!

**Comment by RobertBorghese** [comment]
¯\_(ツ)_/¯ This update looking kinda small, so has some room for a bit of chaos. Has lots of `any`s, but got `bot.ts` working now. Also converted `ban_member.js` to `ban_member.ts` to test typescript actions and show how they may look. 

Sorry this kinda break all your prs, I'll edit/merge them next. 👌 

Also of course DBM editor still needs to be updated to support `.ts` actions, so be careful when using it. I will have a beta branch ready tomorrow. Already mostly ready, but too tired to wait and debug Steam upload bsss.

**Comment by RobertBorghese** [comment]
All right, new `beta` branch on Steam. Passcode is `typescripttime`. Supports `ts` actions, bot.ts, and such. I ping @almeidx since he also hanging around 😘 

Already made issues for specific things to support for TypeScript, so closing this onee.
