### ISSUE TITLE
Editor Bug: Going into an action inside a button on send message fails to open action

### ISSUE THREAD

**Issue by TheMonDon** [RobertBorghese/DBM#48]
Image: https://i.cisn.xyz/piqe4/qOFAZunI52.png/raw

Example Code: https://haste.crafters-island.com/ubicenojam.json

Description:
Create a send message action on a command, create a button and try creating an action to run inside button, or  to edit an existing button. Another send message action will popup with no HTML inside of it. No actions show up inside the action selection menu either.

I tested normal action containers and this does not affect them.

**Comment by RobertBorghese** [comment]
Fixed!
